# Generated by Django 5.1.1 on 2024-10-17 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAUSA_MUERTE',
            fields=[
                ('id_causa_muerte', models.IntegerField(primary_key=True, serialize=False)),
                ('causa_desc', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='COMUNA',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='REGION',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('usuario_FK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=60)),
                ('s_nombre', models.CharField(max_length=60, null=True)),
                ('appaterno', models.CharField(max_length=60)),
                ('apmaterno', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CENTRO_MEDICO',
            fields=[
                ('id_centro_med', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=60)),
                ('comuna_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortalysis.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='PACIENTE',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=60)),
                ('s_nombre', models.CharField(max_length=60)),
                ('appaterno', models.CharField(max_length=60)),
                ('apmaterno', models.CharField(max_length=60)),
                ('numrut', models.IntegerField(max_length=11)),
                ('dvrut', models.CharField(max_length=1)),
                ('edad', models.IntegerField(max_length=120)),
                ('genero', models.CharField(max_length=1)),
                ('comuna_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortalysis.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='PERSONAL_MEDICO',
            fields=[
                ('id_personal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('s_nombre', models.CharField(max_length=60)),
                ('appaterno', models.CharField(max_length=60)),
                ('apmaterno', models.CharField(max_length=60)),
                ('numrut', models.IntegerField(max_length=11)),
                ('dvrut', models.CharField(max_length=1)),
                ('profesion', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('anios_de_trabajo', models.IntegerField()),
                ('anios_en_el_centro', models.IntegerField()),
                ('centro_medico_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortalysis.centro_medico')),
            ],
        ),
        migrations.CreateModel(
            name='DEFUNCION',
            fields=[
                ('id_defuncion', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_muerte', models.TimeField(null=True)),
                ('dia_muerte', models.DateField()),
                ('causa_muerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortalysis.causa_muerte')),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortalysis.centro_medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortalysis.paciente')),
                ('personal_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortalysis.personal_medico')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortalysis.region'),
        ),
    ]
