# Generated by Django 5.1.1 on 2024-10-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMortal',
            fields=[
                ('id_error_mortal', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_error_mortal', models.CharField(max_length=80)),
            ],
        ),
        migrations.RenameModel(
            old_name='CAUSA_MUERTE',
            new_name='CausaIngreso',
        ),
        migrations.RemoveField(
            model_name='personal_medico',
            name='centro_medico_FK',
        ),
        migrations.RemoveField(
            model_name='defuncion',
            name='centro_medico',
        ),
        migrations.RemoveField(
            model_name='defuncion',
            name='personal_medico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_FK',
        ),
        migrations.RenameField(
            model_name='causaingreso',
            old_name='causa_desc',
            new_name='descripcion_causa_ingreso',
        ),
        migrations.RenameField(
            model_name='causaingreso',
            old_name='id_causa_muerte',
            new_name='id_causa_ingreso',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='nombre',
            new_name='nombre_comuna',
        ),
        migrations.RenameField(
            model_name='defuncion',
            old_name='dia_muerte',
            new_name='fecha_defuncion',
        ),
        migrations.RenameField(
            model_name='defuncion',
            old_name='hora_muerte',
            new_name='hora_defuncion',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='apmaterno',
            new_name='a_materno_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='appaterno',
            new_name='a_paterno_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='dvrut',
            new_name='dvrut_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='genero',
            new_name='genero_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='p_nombre',
            new_name='p_nombre_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='s_nombre',
            new_name='s_nombre_paciente',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='nombre',
            new_name='nombre_region',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='region_FK',
        ),
        migrations.RemoveField(
            model_name='defuncion',
            name='causa_muerte',
        ),
        migrations.RemoveField(
            model_name='defuncion',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='comuna_FK',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='numrut',
        ),
        migrations.AddField(
            model_name='comuna',
            name='FK_id_region',
            field=models.ForeignKey(db_column='id_region', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.region'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='FK_id_causa_ingreso',
            field=models.ForeignKey(db_column='id_causa_ingreso', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.causaingreso'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='FK_id_paciente',
            field=models.ForeignKey(db_column='id_paciente', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='FK_id_comuna',
            field=models.ForeignKey(db_column='id_comuna', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.comuna'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad_paciente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numrut_paciente',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id_centro_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_centro_med', models.CharField(max_length=80)),
                ('direccion_centro_med', models.CharField(max_length=60)),
                ('FK_id_comuna', models.ForeignKey(db_column='id_comuna', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='defuncion',
            name='FK_id_centro_medico',
            field=models.ForeignKey(db_column='id_centro_medico', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.centromedico'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='FK_id_error_mortal',
            field=models.ForeignKey(db_column='id_error_mortal', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.errormortal'),
        ),
        migrations.CreateModel(
            name='PersonalMedico',
            fields=[
                ('id_personal_med', models.IntegerField(primary_key=True, serialize=False)),
                ('numrut_pers_med', models.IntegerField(default=0)),
                ('dvrut_pers_med', models.CharField(max_length=1)),
                ('p_nombre_pers_med', models.CharField(max_length=60)),
                ('s_nombre_pers_med', models.CharField(max_length=60, null=True)),
                ('a_paterno_pers_med', models.CharField(max_length=60)),
                ('a_materno_pers_med', models.CharField(max_length=60)),
                ('cargo_pers_med', models.CharField(max_length=50)),
                ('edad_pers_med', models.IntegerField(default=0)),
                ('anios_experienca', models.IntegerField(default=0)),
                ('FK_id_centro_medico', models.ForeignKey(db_column='id_centro_medico', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.centromedico')),
            ],
        ),
        migrations.AddField(
            model_name='defuncion',
            name='FK_id_personal_medico',
            field=models.ForeignKey(db_column='id_personal_medico', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.personalmedico'),
        ),
        migrations.DeleteModel(
            name='CENTRO_MEDICO',
        ),
        migrations.DeleteModel(
            name='PERSONAL_MEDICO',
        ),
        migrations.DeleteModel(
            name='USUARIO',
        ),
    ]
