# Generated by Django 5.1.1 on 2024-10-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortalysis', '0003_alter_defuncion_fk_id_causa_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defuncion',
            old_name='FK_id_causa_ingreso',
            new_name='causa_ingreso',
        ),
    ]
