# Generated by Django 5.1.1 on 2024-10-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalysis', '0004_rename_fk_id_causa_ingreso_defuncion_causa_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defuncion',
            name='causa_ingreso',
        ),
        migrations.AddField(
            model_name='defuncion',
            name='FK_id_causa_ingreso',
            field=models.ForeignKey(db_column='id_causa_ingreso', default=1, on_delete=django.db.models.deletion.CASCADE, to='mortalysis.causaingreso'),
        ),
    ]
