# Generated by Django 5.1.1 on 2024-10-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortalysis', '0005_remove_defuncion_causa_ingreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalmedico',
            old_name='anios_experienca',
            new_name='anios_experiencia',
        ),
    ]
